### ISSUE TITLE
Unable to send SMS: unable to login: jessionid not found

### ISSUE THREAD

**Issue by cyosp** [tomsquest/bouyguessms#1]
Hi Thomas,

In first this issue is an occasion for me to thank you about you excellent work !
I'm using `bouyguessms` at home to send me a notification when my servers daily tasks have a problem. Also in this context I've a daily health check which send me a SMS to check your tool using Bouygues Telecom API is always working.

Unfortunately since the 6th November 2019 I don't receive SMS from my daily SMS health check.
Today I've taken time to investigate the issue.
`bouyguessms` ends with message: `Unable to send SMS: unable to login: jessionid not found`

I think Bouygues has changed its login phase which is now not compatible with `bouyguessms`.

Can you confirm me problem is due to a Bouygues change ?
If yes, could it be possible to have a new working version ?

Thanks,
CYOSP

**Comment by tomsquest** [comment]
Hi @cyosp ,
I am not using Bouygues anymore so I can't check.
The best luck for you is to execute the query one by one to see what is going on.
You can of course fork the project and make a PR.

**Comment by cyosp** [comment]
Hi @tomsquest,

Thank you for your feedback about the issue.
I understand you are not able to help me.
I will see what I'm able to do.

Regards,
CYOSP

**Comment by tomsquest** [comment]
Hi @cyosp ,

I will close this issue and set the status as broken (as per the Readme).
